### ISSUE TITLE
mirai往qq群众发消息时报错

### ISSUE THREAD

**Issue by CitienTZ** [duan602728596/qqtools#133]
## 错误报告

mirai无法往qq群众发送消息,出现如下报错，登陆的qq号为管理员。之前一直好好的，突然有一天就这样了，已经重新安装过mcl和qqtool
![image](https://user-images.githubusercontent.com/15061388/183251176-181bafb1-e4db-4746-a6c8-e5f27de95563.png)
2022-08-06 21:32:21 E/MAH Access: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:146)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:46)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

## 复现步骤

mcl登录qq账号
打开qqtool，完成配置信息
qqtool中登陆配置信息
qq群中发送指令

## 预期行为

qq机器人在qq群中返回指令对应的文本

## 使用环境

- 操作系统：win10专业版 21H2 19044.1826
- 软件版本：
- qqtool 4.10.0/4.9.0
- mcl 2.1.0

**Comment by duan602728596** [comment]
检查一下java版本，plugin版本。看看在命令行下能否发送和接收消息。

**Comment by CitienTZ** [comment]
命令行中能接收到群消息，发送消息的指令是啥？

**Comment by CitienTZ** [comment]
> 检查一下java版本，plugin版本。看看在命令行下能否发送和接收消息。

命令行中能接收到群消息，发送消息的指令是啥？

**Comment by duan602728596** [comment]
> > 检查一下java版本，plugin版本。看看在命令行下能否发送和接收消息。
> 
> 
> 
> 命令行中能接收到群消息，发送消息的指令是啥？

需要你自己看文档了

**Comment by CitienTZ** [comment]
> > > 检查一下java版本，plugin版本。看看在命令行下能否发送和接收消息。
> > 
> > 
> > 命令行中能接收到群消息，发送消息的指令是啥？
> 
> 需要你自己看文档了

在mirai项目里找到相同问题了，tx风控的问题，已解决
