### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by flover-luffy** [duan602728596/qqtools#181]
使用过程当中出现如下错误 
callFunc: "protocol::parseResponse: 13_2"cmd: "login"code: 403event: {}message: "login error: 非法操作或没有权限"retryCount: 0timetag: 1716819986737willReconnect: false[[Prototype]]: Errorname: "NIMError"[[Prototype]]: Object
686_d23c64ddb76eb0c.js:1 TypeError: Failed to fetch
    at e (686_d23c64ddb76eb0c.js:1:7193)
    at l (686_d23c64ddb76eb0c.js:1:8035)
l @ 686_d23c64ddb76eb0c.js:1
index_dd783b2a82359c9.js?1be39004048c3c8cca9e:31 DOMException: signal is aborted without reason
    at Timeout._onTimeout (file:///C:/qqtools-5.4.6-win64/resources/app/view/index_dd783b2a82359c9.js?1be39004048c3c8cca9e:31:49969)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
![image](https://github.com/duan602728596/qqtools/assets/96760096/891770a5-abc7-41e8-8b8a-f0d5a1d1aada)

**Comment by duan602728596** [comment]
SDK不支持浏览器环境了，目前没找到解决办法。
